import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import DriverCard from '../components/DriverCard';
import useSWR from 'swr';
import { instance } from "../lib/apiCalls";
import { useState, useEffect } from 'react';
import { useRouter } from 'next/router';


  
const  fetchDrivers = url => instance.get(url).then(res => res.data).catch(err => {
    throw err
  })





export default function Home() {
  const [loading, setLoading] = useState(false);
  const { data, error } = useSWR("/user/getDrivers", fetchDrivers);

  const router = useRouter();



  useEffect(()=>{

    let token =  localStorage.getItem('token')

    if(!token)  router.push('/user/login')

    instance.defaults.headers.common['Authorization'] = `Bearer ${token}`;

    return () =>{
      setLoading(false);
    }
  },[])




  type DriverObject = {
    id: number,
    email: string,
    name: string
  }

  const handleRequest = (e) =>{
    setLoading(true);

    instance.post(`/user/request/${e}`)
    .then(res => {

      console.log(res,'res')
      router.push('/user/dashboard')

    })
    
  }

  if(loading){
    return (
      <div className="container">
        <div className="row">
          <div className="col-md-12">
            <div className="spinner-border text-primary" role="status">
            </div>
          </div>
        </div>
      </div>
    )
  }


  


  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


     


      <div className='container mt-5'>
        <div className="row">

          { data ? (data.data.map(
            (driver:DriverObject) => (
              <DriverCard  key={driver.id} email={driver.email} name={driver.name} id={driver.id} onRequest={handleRequest} />
            ))) : <h1> loading .. </h1>}
            
        </div>
      </div>


   

  
    </div>
  )
}

